// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetOverdueTasks() {
  return window['go']['main']['App']['GetOverdueTasks']();
}

export function GetTasksByPriority() {
  return window['go']['main']['App']['GetTasksByPriority']();
}

export function GetTasksByStatus() {
  return window['go']['main']['App']['GetTasksByStatus']();
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}
