// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {models} from '../models';

export function CreateTask(arg1:service.CreateTaskInput):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetOverdueTasks():Promise<Array<models.Task>>;

export function GetTasksByPriority():Promise<{[key: number]: Array<models.Task>}>;

export function GetTasksByStatus():Promise<service.TaskList>;

export function ToggleTask(arg1:number):Promise<void>;
